["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
oracle = [
    "./src/interaction/oracle.cairo",
]
wtb_dex = [
    "./src/interaction/wtb_dex.cairo",
]
